require 'custom.remap'
require 'custom.terminal'
require 'custom.googling'
require 'custom.custom_docstring'
require 'custom.load_test_lsp'
require 'custom.python_db_sql'
require 'custom.lualinesetup'
