name: Add LSP file

on: push
permissions:
  contents: write

jobs:

  get_lsp:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch

    - name: Print brach
      run: echo "${{ steps.extract_branch.outputs.branch }}"

    - name: get file
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        mkdir -p ./lsp
        curl -H "Authorization: token ${TOKEN}" https://raw.githubusercontent.com/robhorbury/db_notebook_lsp/main/main -o "./lsp/db_notebook_lsp"
    
    - name: Make binary executable
      run: chmod +x ./lsp/db_notebook_lsp
    
    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"

    - name: Commit files # commit the output folder
      run: |
        git add .
        git commit -m "Added built go files"
        git push origin ${{ steps.extract_branch.outputs.branch }}


